version: '3'
services:
  app:
    build:
      context: .
      target: app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - api
  api:
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    ports:
      - 5001:5000

  train:
    build:
      context: .
      target: train
      dockerfile: Dockerfile
