version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - 5050:5050
    environment:
      API_URL: http://api:5000/predict
    depends_on:
      - api

  api:
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    volumes:
      - "./data:/app/data"
    ports:
      - 5000:5000
