version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - 5000:5000

    depends_on:
      - api
  api:
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    ports:
      - 5050:5050

  train:
    build:
      context: .
      target: train
      dockerfile: Dockerfile
